name: test-other

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: cat test.txt
