name: Testing
on:
  schedule:
    - cron: 0 10 * * *
  workflow_dispatch:
  issue_comment:
    types: 
      - created

jobs:

  Check-Comments:
    name: Check for comments
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.sha.outputs.result }}
    steps:
      - name: Get PR SHA
        if: ${{ github.event.issue.pull_request && github.event.comment.body == '/test' }}  
        id: sha
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha

  Check-For-Changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.commits.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - name: Check for commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV
      - id: commits
        run: echo "changes=$NEW_COMMIT_COUNT" >> "$GITHUB_OUTPUT"

  Integration-Test:
    name: ${{ matrix.version }} - Integration Tests
    runs-on: macos-latest
    needs: [Check-For-Changes, Check-Comments]
    if: ${{ needs.Check-For-Changes.outputs.changes > 0 || needs.Check-Comments.outputs.sha || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        version: [ 1.56.0, latest, insider ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.Check-Comments.outputs.sha || github.sha }}
      - run: echo "lets gooooooooo" ${{ matrix.version }}