name: Test tagging

on:
  workflow_dispatch:
  push:
    tags: '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          node -e 'console.log(process.env.EVENT)'
          echo "${{ env.EVENT }}"
        env:
          EVENT: "${{ github.event.release.tag_name }}"
