name: test-again2

on:
  release:
    types: [created]
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - run: cat test.txt
    - run: echo "hello2!"
